# Config for Jekyll static site generator.

exclude:
  - docs

# Standard template variables like {{ site.title }}, {{ site.email }}, and so
# on, are below. Custom variables like {{ site.myvariable }} are in the next
# block separated by dashes.
 
title: Гарадскі дашборд
email: help@opendata.by
description: Minsk City Dashboard, built in open source way with open data.
baseurl: ""
url: "city.opendata.by"
#twitter_username: jekyllrb

collections:
  indicators:
    output: true

# --- custom variables for city dashboard ------------------------------------

source_repo: "https://github.com/opendataby/city-dashboard"

